### ISSUE TITLE
Change Hospitales and add Acuerdos aseguradoras y colectivos instead

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#101]
On the old website http://www.futurehealthbiobank.es/precios-conservacion-celulas-madre there is a section with the below screenshot.

![Screen Shot 2016-06-01 at 10.33.27.png](https://zube.io/files/maricarstubley/9f27217a58ca98a5eb5c9859f8a4cdd0.png)

we need the content of that section adding to this page Acuerdos aseguradoras y colectivos.

Also add this copy at the top:

Acuerdos con aseguradoras, grupos hospitalarios, empresas y colectivos

Por favor póngase en contacto con nuestro equipo de Atención al Cliente y pregunte por sus condiciones económicas especiales en los teléfonos 900 206 184 - 914 314 703, o bien por email en info@futurehealth.es

**Comment by mcatena** [comment]
@maricarstubley title of the page changed....Shall i use the same segment of the accreditations to build the page?Where i can find the images?

**Comment by maricarstubley** [comment]
Images - we don't have any
Segments -  Whatever you think is suitable

**Comment by mcatena** [comment]
http://fhbb.staging.wpengine.com/es/acuerdos-aseguradoras-y-colectivos/
