### ISSUE TITLE
Image not translated

### ISSUE THREAD

**Issue by mcatena** [maricarstubley/fhbb-ticket#103]
http://fhbb.staging.wpengine.com/es/servicios/conservar-celulas-madre-cordon-umbilical/conservar-celulas-madre-cordon-umbilical/celulas-madre-sangre-cordon-umbilical/guia-proceso-recogida-y-conservacion-pasos-recogida-sangre-cordon-umbilical/
and

http://fhbb.staging.wpengine.com/es/servicios/conservar-celulas-madre-cordon-umbilical/conservar-celulas-madre-cordon-umbilical/celulas-madre-tejido-cordon-umbilical/guia-proceso-recogida-y-conservacion-pasos-recogida-tejido-cordon-umbilical/

**Comment by mcatena** [comment]
All the processes images are now translated.

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/informacion-sobre-conservar-celulas-madre/nuevo-ensayo-clinico-tratamiento-ictus-pediatrico-con-celulas-madre/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/informacion-sobre-conservar-celulas-madre/resultados-prometedores-tratamiento-rdeb-con-celulas-madre/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/informacion-sobre-conservar-celulas-madre/nuevo-ensayo-clinico-tratamiento-artrosis-con-celulas-madre/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/informacion-sobre-conservar-celulas-madre/como-elegir-banco-celulas-madre-fiable/

**Comment by maricarstubley** [comment]
What's happened here?! Why are the images still in english?

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/informacion-sobre-conservar-celulas-madre/como-elegir-banco-celulas-madre-fiable/

The middle box under Ayuda y consejos is in english. Can you ask Catherine about this?

**Comment by mcatena** [comment]
Done changed with a different icon
