### ISSUE TITLE
Update Horizon to Foresight

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#109]
http://fhbb.staging.wpengine.com/pt/sobre-nos/o-que-fazemos/

Why is this still in Horizon?

**Comment by maricarstubley** [comment]
And also this one http://fhbb.staging.wpengine.com/pt/servicos/servicos-de-diagnostico/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/pt/precos/diagnostics-prices/

**Comment by mcatena** [comment]
Done
