### ISSUE TITLE
Form is not showing

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#110]
http://fhbb.staging.wpengine.com/pt/solicitar-uma-brochura/

Where is the form on this page?

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/pt/contacte-nos/

**Comment by mcatena** [comment]
I'm sorry but i have no field to put them in.

**Comment by maricarstubley** [comment]
I've added this now.

**Comment by mcatena** [comment]
http://fhbb.staging.wpengine.com/pt/solicitar-uma-brochura/

Request a brochure segment is missed....

**Comment by maricarstubley** [comment]
Added.

**Comment by mcatena** [comment]
Complete
