### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mcatena** [maricarstubley/fhbb-ticket#121]
I can not see the pages after i created them

This is the error
Notice: Trying to get property of non-object in /nas/content/staging/fhbb/wp-content/themes/future-health-biobank/functions.php on line 688

Fatal error: Call to a member function get_settings() on a non-object in /nas/content/staging/fhbb/wp-content/themes/future-health-biobank/functions.php on line 689

**Comment by maricarstubley** [comment]
Done
