### ISSUE TITLE
Where have these titles come from?

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#128]
Elige tu país -  http://fhbb.staging.wpengine.com/es/elige-tu-pais
Inscríbase al boletín - http://fhbb.staging.wpengine.com/es/inscribase-al-boletin

**Comment by maricarstubley** [comment]
Can you tell me where in the excel these are in please?

**Comment by mcatena** [comment]
I don't know....i can not find them...i'm sorry maybe is something i done before the complain....

**Comment by Elpida-Mav** [comment]
Eva emailed the correct text on 16/6

Inscríbase al boletín --> change to: Suscríbase a nuestro boletín 
Elige tu país --> Change to: Seleccionar país

**Comment by maricarstubley** [comment]
@mcatena Can you amend please

**Comment by mcatena** [comment]
Done
