### ISSUE TITLE
Dental pulp

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#132]
Please change dental pulp to segment 14 on this page http://fhbb.staging.wpengine.com/pt/servicos/armazenamento-de-celulas-estaminais/

The reason for this change is that the adipose tissue is not a service in Portugal

I will send across the sub text when I get this.

**Comment by maricarstubley** [comment]
Here is the sub text:

Os dentes de leite e dentes saudáveis de adulto são fontes ricas de células, oferecendo aos pais uma segunda oportunidade para armazenar as células dos seus filhos.

**Comment by mcatena** [comment]
Done
