### ISSUE TITLE
Collection process pages

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#133]
Not sure why but the icons appear to have a pink background instead of the white which I've used in the UK, see this example http://fhbb.staging.wpengine.com/our-services/stem-cell-banking/umbilical-cord-stem-cell-banking/cord-tissue-stem-cell-banking/cord-tissue-stem-cell-collection-process/. 

It's quite hard to see the icons that you've added and they aren't very sharp like the ones I've done for the UK.

Also I think if there's no writing or amends needed for the icon we should be using the same icons through out every website to save time and redoing the icons each time. I have found different sizes of icons like this http://fhbb.staging.wpengine.com/pt/servicos/armazenamento-de-celulas-estaminais/sangue-e-tecido-do-cordao-umbilical/tecido-do-cordao-umbilical/cord-tissue-stem-cell-collection-process/ used for both Spain,Portugal and Italy and it's looking really messy and inconsistent. This does need to change to match exactly what I've done for the UK.

Lastly on the URL above I've noticed that step 5 is the only one with a pink background. Not sure why this is but as you're making these changes anyway can you change the icon to have a white background. It also needs to be the same size as it will look odd if it's a completely different size or file type.

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/pt/servicos/armazenamento-de-celulas-estaminais/sangue-e-tecido-do-cordao-umbilical/celulas-estaminais-do-sangue-e-tecido-do-cordao-umbilical/processo-de-recolha/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/pt/servicos/armazenamento-de-celulas-estaminais/sangue-e-tecido-do-cordao-umbilical/tecido-do-cordao-umbilical/cord-tissue-stem-cell-collection-process/

**Comment by maricarstubley** [comment]
What's happened here?!

http://fhbb.staging.wpengine.com/pt/servicos/armazenamento-de-celulas-estaminais/polpa-dentaria/o-processo-de-recolha-da-polpa-dentaria/

![Screen Shot 2016-06-16 at 00.45.13.png](https://zube.io/files/maricarstubley/bcd341d6609861bb0a54d2022b3162cb.png)

**Comment by mcatena** [comment]
@maricarstubley All fixed
