### ISSUE TITLE
Step 4 and step 6 images need updating

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#134]
http://fhbb.staging.wpengine.com/pt/servicos/armazenamento-de-celulas-estaminais/sangue-e-tecido-do-cordao-umbilical/sangue-do-cordao-umbilical/processo-de-recolha-de-celulas-estaminais-do-sangue-do-cordao-umbilical/

Please check with Catherine if these have been done. Please update for all countries

**Comment by mcatena** [comment]
@maricarstubley waiting for the translation for collection kit in italian and portuguese

**Comment by mcatena** [comment]
@maricarstubley changed. Now in all website are exactly the same....
