### ISSUE TITLE
Second banner

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#136]
The text in the ribbon doesn't match the curve on the ribbon and this isn't an acceptable quality to add on our websites!

Please make sure before adding any banners that it looks visually pleasing. Can you ask Catherine to make this amend or tell you where it is so you can amend it.

![Screen Shot 2016-06-15 at 23.41.45.png](https://zube.io/files/maricarstubley/98516e68c64461e63096154225ece2f5.png)

**Comment by mcatena** [comment]
Done...have look if is ok now please
