### ISSUE TITLE
The 'S' and 'T' should be capitals!

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#138]
![Screen Shot 2016-06-15 at 23.48.01.png](https://zube.io/files/maricarstubley/8d2de49c4ae9333eb617af6f63810d1f.png)

Can you make sure this amend is done for every site so it doesn't waste time of having to redo it again. This has been briefed in to Catherine so i would wait for this to be done.

**Comment by maricarstubley** [comment]
This page needs to be amended as well http://fhbb.staging.wpengine.com/pt/servicos/armazenamento-de-celulas-estaminais/sangue-e-tecido-do-cordao-umbilical/

**Comment by mcatena** [comment]
Done
