### ISSUE TITLE
About us picture at top needs changing

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#140]
![Screen Shot 2016-06-15 at 23.56.50.png](https://zube.io/files/maricarstubley/b292b096fb5d563635fb8cc790b6fb7b.png)

But wait for an update as Portugal will send through images for us to update this.

http://fhbb.staging.wpengine.com/pt/sobre-nos/

**Comment by mcatena** [comment]
@maricarstubley i changed the banner.. there are 4 choice i choose that one because is the most complete with all the information....let me know if is ok for you
