### ISSUE TITLE
Box around the icon

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#141]
![Screen Shot 2016-06-15 at 23.59.33.png](https://zube.io/files/maricarstubley/04424330464f8dbebf17af5786706cf3.png)

I keep seeing this sort of icon in a box. It should haven't a box it should look more like the icons that sit in the collections process icons. Here's the link to the above image http://fhbb.staging.wpengine.com/pt/sobre-nos/

It should look more like:

![Screen Shot 2016-06-16 at 00.04.09.png](https://zube.io/files/maricarstubley/6714d0aecc08ecaf140be3a1c910c4ef.png)

Or the third image in segment 24 here http://fhbb.staging.wpengine.com/pt/servicos/armazenamento-de-celulas-estaminais/polpa-dentaria/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/pt/sobre-nos/porque-escolher-nos/

**Comment by mcatena** [comment]
Done

**Comment by mcatena** [comment]
Changed in all sites
