### ISSUE TITLE
Update Meet the team

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#143]
http://fhbb.staging.wpengine.com/pt/sobre-nos/equipa/

Portugal will provide the pictures and content. I will update this ticket when I have it.

**Comment by maricarstubley** [comment]
You will find the images in NEW WEBSITE > PT > Meet the team images

**Comment by mcatena** [comment]
@maricarstubley Updated...but some contents are still missing...wrote an email

**Comment by mcatena** [comment]
Done
