### ISSUE TITLE
Any instance of 'UK' in 'UK Managing Director' should not be add from now on

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#144]
![Screen Shot 2016-06-16 at 00.13.47.png](https://zube.io/files/maricarstubley/73abbfc34f809d7dc664af89c84c3d7d.png)

This keeps cropping up as an amend. Please can you make sure this doesn't occur for all other websites.

**Comment by mcatena** [comment]
I took out all UK and added what is on the spread sheet Direttore Esecutivo Regno Unito

**Comment by maricarstubley** [comment]
Any mentions of the United Kingdom or the UK under Roger should be taken out as requested above.

**Comment by mcatena** [comment]
Done...
