### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#146]
http://fhbb.staging.wpengine.com/pt/sangue-tecido-possibilidades-tratamento/

**Comment by maricarstubley** [comment]
And this page http://fhbb.staging.wpengine.com/pt/ensaios-clinicos-celulas-estaminais/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/pt/precos/diagnostics-prices/

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Why are the images massive for these pages? Seems a bit over the top to me.

http://fhbb.staging.wpengine.com/pt/sangue-tecido-possibilidades-tratamento
http://fhbb.staging.wpengine.com/pt/ensaios-clinicos-celulas-estaminais

**Comment by mcatena** [comment]
Done
