### ISSUE TITLE
Payment image missing in Seg 5

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#147]
http://fhbb.staging.wpengine.com/pt/servicos/servicos-de-diagnostico/teste-pre-natal-nao-invasivo/nipt-competitor-chart/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/pt/servicos/servicos-de-diagnostico/rastreio-para-recem-nascido/o-novo-processo-de-recolha-para-o-rastreio-a-recem-nascidos/

**Comment by mcatena** [comment]
Done
