### ISSUE TITLE
Customer focus in Seg 24

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#148]
http://fhbb.staging.wpengine.com/pt/sobre-nos/equipa/

Catherine has been briefed. Please update when she has done the graphic

**Comment by mcatena** [comment]
@maricarstubley We still don't have any translation for that....Shall i change the icon?

**Comment by maricarstubley** [comment]
As mentioned before can you not add in my for review as this isn't complete

**Comment by mcatena** [comment]
Done
