### ISSUE TITLE
What's happened to the text in the second banner?

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#152]
http://fhbb.staging.wpengine.com/it/

Manuel, please check your work against the excel sheet. I don't speak the language and certainly don't understand it but I can see that it looks wrong! I've had a look in the excel sheet and you've copied the wrong sections for banner two. If you're unsure how it should read or look just check against the UK site as mentioned many times before.

**Comment by mcatena** [comment]
Done
