### ISSUE TITLE
Text in banner looks really squashed

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#155]
![Screen Shot 2016-06-16 at 02.49.54.png](https://zube.io/files/maricarstubley/ce6900b2bc54fe9be4f4ee23f0515e32.png)

and the text in this one looks stretched
![Screen Shot 2016-06-16 at 02.50.52.png](https://zube.io/files/maricarstubley/b4087d8f81791cf5f829faf670b2815a.png)

**Comment by mcatena** [comment]
Done. Have look please if are all ok....Thanks
