### ISSUE TITLE
Horizon is massive

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#157]
http://fhbb.staging.wpengine.com/it/prezzi/diagnostics-prices/
![Screen Shot 2016-06-16 at 03.04.18.png](https://zube.io/files/maricarstubley/e1ca46ec736aab8e481ee4f083367096.png)

**Comment by maricarstubley** [comment]
And the services links to the same page

**Comment by mcatena** [comment]
@maricarstubley Done and created the two diagnostics price pages but i have no contents for them on the spreadsheet
