### ISSUE TITLE
Does these pages need adding?

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#159]
http://fhbb.staging.wpengine.com/it/stem-cell-clinical-trials
http://fhbb.staging.wpengine.com/it/cord-blood-treatment-possibilities

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/it/blog/

**Comment by mcatena** [comment]
@maricarstubley i have not translation yet for the first two i will put english for now and i have no posts for the blog too

**Comment by mcatena** [comment]
Added english contents on the pages
