### ISSUE TITLE
The text is smaller in these boxes for Portugal than UK

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#161]
![Screen Shot 2016-06-16 at 11.01.03.png](https://zube.io/files/maricarstubley/5e9be8282ae64b107da2b4f6e6fd2487.png)

**Comment by mcatena** [comment]
@maricarstubley Please have look if they need more change

**Comment by maricarstubley** [comment]
@mcatena Please refer to the UK to see if they match before sending back to me for checking. 

It does look similar and better but not the same therefore not consistent.

**Comment by maricarstubley** [comment]
@mcatena just wondering why there are brackets around the bottom text?

**Comment by mcatena** [comment]
@maricarstubley because were in the spreadsheet

**Comment by mcatena** [comment]
Done
