### ISSUE TITLE
Please format the blog better

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#173]
Some of the text is just put together as one giant text. It's a bit hard to read. Can you add paragraphs where neccessary.

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Can the text go underneath instead of wrapping round the image.

http://fhbb.staging.wpengine.com/es/future-health-gana-un-premio-de-responsabilidad-social/

**Comment by mcatena** [comment]
Done
