### ISSUE TITLE
Replace text in Portugal

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#175]
In http://fhbb.staging.wpengine.com/pt/blog/ajuda/

Please replace:
Header: A seção de Programa Cliente inclui todas as nossas ofertas exclusivas, para clientes e novos clientes.

Sub text: Da nossa prestigiada campanha "Recomendar um Amigo" às nossas competitivas ofertas de preço, esta secção oferece aos nossos antigos e novos clientes descontos únicos e exclusivos.

**Comment by mcatena** [comment]
Done
