### ISSUE TITLE
http://fhbb.staging.wpengine.com/pt/programa-de-fidelizacao/

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#178]
Can you take out the title as it's repeated in the H1 tag so no need for this.

Replace sub text: Na Future Health Biobank premiamos os nossos clientes, e é por isso que criámos o programa de fidelização, que oferece a todos os que já são nossos clientes um desconto de especial caso solicitem o mesmo serviço uma segunda ou terceira vez.

**Comment by maricarstubley** [comment]
Bottom text replace with: Para saber mais sobre o nosso programa de fidelização contacte a nossa atenciosa equipa de apoio ao cliente linha gratuita: 800 103 480 e-mail info@futurehealth.pt.

**Comment by mcatena** [comment]
Done
