### ISSUE TITLE
Pacote gémeos

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#179]
Should the URL be http://fhbb.staging.wpengine.com/twin-package/? Looks to me like it's still in english.
1. Change H1 tag and URL to Gémeos não idênticos.
2. Also, the formatting doesn't appear to look like UK
3. Header title change to: Se está à espera de gémeos não idênticos, precisará de dois kits de recolha. É com muito agrado que oferecemos aos pais de gémeos não-idênticos um desconto especial. Contacte a nossa atenciosa equipa de apoio ao cliente linha gratuita: 800 103 480 e-mail info@futurehealth.pt.

**Comment by mcatena** [comment]
Done
