### ISSUE TITLE
Promessa de preço

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#180]
http://fhbb.staging.wpengine.com/pt/promessa-de-preco-2/

Are there two of these pages? The URL should have a 2 on the end.

Change header title to: Future Health Biobank promessa de preço
Sub text: Na Future Health Biobank oferecemos a garantia de promessa de preço no nosso serviço de células estaminais. Caso lhe ofereçam um preço mais baixo para um serviço idêntico (mesmas caraterísticas e condições), comprometemo-nos a reduzir o nosso preço em pelo menos €100. Contacte a nossa equipa de apoio ao cliente linha gratuita: 800 103 480 e-mail info@futurehealth.pt

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Could you make the email and phone number clickable please.

**Comment by mcatena** [comment]
Done
