### ISSUE TITLE
Seg 24

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#189]
On this page seg 24 has a few amends:
http://fhbb.staging.wpengine.com/pt/sobre-nos/equipa/

Box 1: I'll send you over this graphic
Box 2: Can we remove this graphic and change it for one that has been updated? In Portugal they said that the pig is more associated with ham and supermarkets. I think Catherine has an update graphic for this.
Box 3: Still in english

**Comment by mcatena** [comment]
Done
