### ISSUE TITLE
Paragraph on these pages look really bold

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#192]
It's looks very untidy and very hard to read. This request has been asked previously. 

Can you make sure you add paragraph tags around to make sure the formatting looks neat and the same as UK.

http://fhbb.staging.wpengine.com/es/panel-informativo/informacion-sobre-conservar-celulas-madre/como-elegir-banco-celulas-madre-fiable/

Can you check this page to make sure it's the same http://fhbb.staging.wpengine.com/advice-panel/stem-cell-banking-advice/how-to-choose-a-reliable-stem-cell-bank/

**Comment by mcatena** [comment]
@maricarstubley done...but i done it million times...it's no normal that overtime you enter in a page it losts the formatting...
