### ISSUE TITLE
Segment 24 -  Icon in middle box is in english

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#194]
Please amend.

**Comment by maricarstubley** [comment]
On this page the 1st and 2nd box is in english:

http://fhbb.staging.wpengine.com/pt/recomendar-a-um-amigo/

Also the main banner at the top is squashed

**Comment by mcatena** [comment]
@maricarstubley Done....i will change the icon in all website to make it consistent...because took out words and made it bigger...

Please let me know if i have to change it on uk too
