### ISSUE TITLE
Interest free payment plan

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#195]
![Screen Shot 2016-06-29 at 00.04.37.png](https://zube.io/files/maricarstubley/5a8408107ae8db5755957a832d7d7fb0.png)

http://fhbb.staging.wpengine.com/pt/sobre-nos/porque-escolher-nos/

As you've updated the image above this icon should also update everywhere else. For example the icon in segment 24 should be consistent with update of the image.

**Comment by mcatena** [comment]
Done
