### ISSUE TITLE
Thank you messages go to UK

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#198]
If you've done this can you in future add the links on here.

If you haven't done these can you update.

**Comment by mcatena** [comment]
http://fhbb.staging.wpengine.com/pt/obrigada-pela-sua-mensagem/

http://fhbb.staging.wpengine.com/pt/obrigada-por-solicitar-o-envio-da-brochura/

http://fhbb.staging.wpengine.com/pt/obrigada-por-subscrever-a-nossa-newsletter/
