### ISSUE TITLE
Amends for Spain

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#202]
Por qué Future Health Biobank
·         Help and advice: Box 1&2 use different icons, these are too small [use the burgundy coloured ones that are more simple] like we use on the help and advice section on this page: http://fhbb.staging.wpengine.com/es/servicios/conservar-celulas-madre-cordon-umbilical/celulas-madre-sangre-y-tejido-cordon-umbilical/

Programa de fidelización
·         Help and advice: Change banners used to red ones [same point as Por qué Future Health Biobank]

Recomiende a un amigo
·         Help and advice: box 1 change to burgundy infographic

Programa de fidelización
·         Help and advice: box 1 change to burgundy infographic

Descuentos para gemelos o mellizos
Help and advice: box 1 change to burgundy infographic

Advice panel:

Cómo elegir un banco de células madre fiable
·         Help and advice : Change 3rd infographic to burgundy style

¿Cómo se recogen las células madre del cordón umbilical?
·         Help and advice : Change 3rd infographic to burgundy style

Más fondos para la investigación de células madre de la sangre del cordón
·         Help and advice : Change 3rd infographic to burgundy style

Descubrimiento relacionado con la diabetes
·         Help and advice : Change 3rd infographic to burgundy style

Un paso más cerca del tratamiento de la parálisis cerebral con células madre
·         Help and advice : Change 3rd infographic to burgundy style

¿Tiene Future Health Biobank su propio laboratorio?
·         Help and advice : Change 3rd infographic to burgundy style

¿Qué pasa si no conservo las células madre de mi cordón umbilical?
·         Help and advice : Change 3rd infographic to burgundy style

Primer ensayo de sangre del cordón para el VIH
·         Help and advice : Change 3rd infographic to burgundy style

Prometedores resultados del tratamiento de la EADR con células madre
·         Help and advice : Change 3rd infographic to burgundy style
·         Split up the text as looks too dense

Nuevo ensayo clínico en marcha para el tratamiento del ictus pediátrico
·         Help and advice : Change 3rd infographic to burgundy style

Nuevo ensayo clínico en marcha para el tratamiento de la artrosis usando células madre
·         Help and advice : Change 3rd infographic to burgundy style
·         Split up the text as looks too dense

¿En qué se diferencia el TPNI de una amniocentesis?
·         Help and advice : Change 3rd infographic to burgundy style
Familia Escalona – Yuste
·         Help and advice: 3rd box [diabetes] isn’t correct length [we have the correct copy in other parts of the website

Familia Osa – Mari
·         Help and advice: 3rd box [diabetes] isn’t correct length [we have the correct copy in other parts of the website

Familia Civil – Pérez
·         Help and advice: the three boxes aren’t the right sizes

**Comment by mcatena** [comment]
Done
