### ISSUE TITLE
Add Chelsea & Westminster hospital

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#203]
Can you add in here please http://fhbb.staging.wpengine.com/hospitals

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Can you add these in also:

Burton Hospitals NHS Trust
MOVE City Birmingham to Birmingham City Hospital
Cossham Hospital
Dumfries & Galloway Hospital
Forth Valley Royal Hospital
Imperial College Healthcare NHS Trust
Jersey General Hospital
Lindo Wing, St Marys Hospital
Manchester Royal Hospital
Ninewells Hospital
Orpington Hospital
Port Talbot Hospital
Princess Alexandra Hospital
Princess Royal Hospital Telford
Rotherham Hospital
Rosie Maternity Hospital
St Georges Hospital
Sheffield Teaching Hospital
St Marys Hospital Newport
St peters Hospital Maldon
Stoke Mandeville Hospital
University Hospital Coventry
University Hospital Crosshouse
University Hospital Lewisham
Wycombe Hospital

**Comment by mcatena** [comment]
Done
