### ISSUE TITLE
Blog page Italy - Portugal

### ISSUE THREAD

**Issue by mcatena** [maricarstubley/fhbb-ticket#212]
I can not upload the main banner... Blog template segment missed

THX

**Comment by maricarstubley** [comment]
Fixed

**Comment by mcatena** [comment]
I still can not see it in portugal...tried to fixed but in this case i don't know how...

**Comment by maricarstubley** [comment]
No worries. Fixed now. 

Sorry to be pain but can you add future requests my tasks instead of backlog. It's not often I check in column so I'm afraid I'm going to miss any requests.
