### ISSUE TITLE
Random full stop after the pink title

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#214]
http://fhbb.staging.wpengine.com/pt/servicos/armazenamento-de-celulas-estaminais/polpa-dentaria

I don't think this should be in there?

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
It should be in there. If you notice the other 4 services you'll see there is no full stop. Can you take this out?

**Comment by mcatena** [comment]
Done
