### ISSUE TITLE
Price page - Italy

### ISSUE THREAD

**Issue by mcatena** [maricarstubley/fhbb-ticket#223]
On this page : http://fhbb.staging.wpengine.com/it/prezzi/prezzi-della-conservazione-delle-cellule-staminali/prezzi-della-conservazione-delle-cellule-staminali-del-cordone-ombelicale/pagamenti-rateali-premium-senza-interessi-per-sangue-e-tessuto-cordonale/

Why are the words Conservazione delle cellule staminali da sangue e tessuto cordonale so big? This looks really strange. The page should look more along the lines of this: http://futurehealthbiobank.com/es/precios/precios-conservacion-celulas-madre-cordon-umbilical/pago-mensual-sin-intereses/

In front end is the same

Thx

**Comment by maricarstubley** [comment]
Did you check the UK? If it's the same then that's what it should be.
