### ISSUE TITLE
Advice panel Italy

### ISSUE THREAD

**Issue by mcatena** [maricarstubley/fhbb-ticket#224]
http://fhbb.staging.wpengine.com/it/consulenza/

The arrow for this button needs to be on the same line as the copy: Visualizza tutti le informazioni sulla conservazione delle cellule staminali 

Thanks

**Comment by maricarstubley** [comment]
This is far too long to be a CTA link and not accepted. Please send a request for this to be amended.

Rememeber it's a call to action and therefore not great for the customers user journey!

**Comment by mcatena** [comment]
Email sent

**Comment by maricarstubley** [comment]
This task needs to stay with you until it's complete.
