### ISSUE TITLE
Missing image in middle box

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#237]
Please can you see why the icon is missing from the middle box http://fhbb.staging.wpengine.com/advice-panel/stem-cell-banking-advice/can-i-contact-customer-care-team/

**Comment by maricarstubley** [comment]
The icon in the first box is missing here aswell. http://fhbb.staging.wpengine.com/advice-panel/stem-cell-banking-advice/future-health-biobank-laboratory/

**Comment by mcatena** [comment]
Done
