### ISSUE TITLE
PT amend on Interest free section

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#238]
On this page http://fhbb.staging.wpengine.com/pt/precos/celulas-estaminais/preco-do-servico-do-cordao-umbilical/

In Planos de prestações sem juros
Remove: Sabemos que ter um bebé pode ser um momento dispendioso, e é por isso que tentamos facilitar as coisas proporcionando planos de pagamento até 24 meses sem juros

Replace with: Disponibilizamos diversas opções de pagamento, incluindo planos de pagamento sem juros.

**Comment by mcatena** [comment]
Done
