### ISSUE TITLE
PT - What we do

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#241]
http://fhbb.staging.wpengine.com/pt/sobre-nos/o-que-fazemos/

Remove: 
Disponibilizamos três serviços básicos em termos de armazenamento de células estaminais: cordão umbilical e polpa dentária e tecido adiposo.

Replace with: 
Disponibilizamos três serviços básicos em termos de armazenamento de células estaminais: cordão umbilical, polpa dentária e tecido adiposo. Para mais informações sobre armazenamento de células estaminais do tecido adiposo contacte-nos.

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Under Testes de Diagnóstico: Please put the word “Diagnostics” on Italic where it starts "O nosso departamento..."

Under Teste pré-natal não invasivo:

Please remove: Sindrom Down
Replace with: Sindrome de Down

**Comment by mcatena** [comment]
Done
