### ISSUE TITLE
PT -  Our global family

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#242]
In the page http://fhbb.staging.wpengine.com/pt/sobre-nos/

Remove: Dois bancos próprios, na Suíça e no Reino Unido
Replace with: Dois “laboratórios” próprios, na Suíça e no Reino Unido

**Comment by maricarstubley** [comment]
And also find 115.000 in the text below the main image and replace with 125.000

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
This ticket doesn't look like it's done.

**Comment by mcatena** [comment]
Sorry i changed inside the text and not the h1

now it's done
