### ISSUE TITLE
New hospital-based page

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#261]
Can you create a new page in staging please with the below content:

Future Health Biobank is proud to collect more stem cell samples from UK hospitals than any other bank

Future Health Biobank offers a hassle free service for any expectant parent looking to store their child’s stem cells. We organise the entire collection for you and liaise with your chosen hospital, birth centre or private wing to ensure everything runs smoothly on the day.
To see an extensive, but not exhaustive, list of hospitals we have collected from this year please click here (http://futurehealthbiobank.com/blog/a-helping-hand/hospitals/) 
In addition, we also routinely collect from the top five private maternity hospitals in London:
    ⁃ The Portland Hospital
    ⁃ St Mary’s Hospital, Paddington - The Lindo Wing
    ⁃ Chelsea & Westminster - The Kensington Wing
    ⁃ Guy’s and St Thomas’ – Westminster Suite
    ⁃ Queen Charlotte’s & Chelsea – Sir Stanley Clayton Ward
We always work alongside your private consultant obstetricians to ensure everything runs smoothly on the big day. Should you choose to bank your child’s stem cells with us you will be joining the other 75,000 families that have safely stored their stem cells with Future Health Biobank [link to Why choose us page].
Why store your baby’s umbilical cord stem cells?
The umbilical cord is a precious source of stem cells which is only available at the time of your child’s birth. The stem cells found within the umbilical cord contain life-saving stem cells unique to your baby. Should these stem cells be required for future treatment, they will be a 100% match to your baby and can potentially also be used for a sibling or wider family member. For more information on storing your child’s stem cells, please visit our umbilical cord banking page. [link to CBCT page].
How affordable is the service?
Future Health Biobank will store your child’s cord blood for 25 years. You can opt to spread the cost of the service using the interest free instalment plan starting from as a little as £83 a month, for just 18 months. 
We understand that having a baby is an expensive time, which is why we offer a range of payment options, including interest free payment plans, for more information visit our pricing page [link to CBCT pricing page].
For further information on the hospitals and consultants we work with, please call 0115 967 7707 or email custcare@fhbb.com 

URL should follow as /blog/a-helping-hand/private-hospital-partnerships/

**Comment by mcatena** [comment]
Done
http://fhbb.staging.wpengine.com/blog/a-helping-hand/private-hospital-partnerships/
