### ISSUE TITLE
Helping hand and Special offers page

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#262]
We need to create a new page for the Special offers on the Swiss English website and have a slightly different layout for helping hand. Needs to be the same setup as what we have done for Swiss French so refer to this when you need to understand what the page looks like.

The page we need to copy for helping hand looks like this page http://fhbb.staging.wpengine.com/ch-fr/blog/besoin-daide. We have a main banner at the top to link to the special offers page. Then we need 3 boxes below with Recommend a friend, Twin package and Loyality scheme.

Lastly the hospitals banner at the bottom. Can you make it sit exactly like how I've done it for the Swiss french with the text on top of the box rather than above the box.

Then we need to create the special offers page like this page http://fhbb.staging.wpengine.com/ch-fr/blog/offre-speciale/. You can get the content from this page http://www.futurehealthbiobank.ch/en/special-offer

Can you then link the homepage banner, first slide to the special offers page. The copy should be the same as the old swiss english website.

Big text: SPECIAL SEPTEMBER OFFER 
Small text: Order a kit before 30th September
and receive a 10% discount.
Link: Find out more

Let me know if you need to run through this further.

**Comment by mcatena** [comment]
http://fhbb.staging.wpengine.com/ch-en/blog/a-helping-hand/exclusive-offer/

**Comment by maricarstubley** [comment]
Also please keep the page name as is - Helping hand

The main headline and sub text please add:

Big text: Look out for our exclusive offers and promotions for our customers Future Health Biobank
Small text: At Future Health Biobank, we are committed to our customers to offer the best value for money. Please visit our special offers page for more information.

**Comment by maricarstubley** [comment]
The banner I am currently requesting

**Comment by mcatena** [comment]
The banner is already in
What mean Also please keep the page name as is - Helping hand?

**Comment by mcatena** [comment]
Done

http://fhbb.staging.wpengine.com/ch-en/blog/helping-hand/

i need a copy for the first box recommend a friend

**Comment by maricarstubley** [comment]
Can you add this in for now 'From our highly considered Recommend a Friend scheme to our competitive Price Promise offering, this section offers our loyal customers unique and exclusive discounts.'

**Comment by mcatena** [comment]
Done
