### ISSUE TITLE
Helping hand and special offers

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#263]
We need to create a new page for the Special offers on the Swiss German website and have a slightly different layout for helping hand. Needs to be the same setup as what we have done for Swiss French so refer to this when you need to understand what the page looks like.

The page we need to copy for helping hand looks like this page http://fhbb.staging.wpengine.com/ch-fr/blog/besoin-daide. We have a main banner at the top to link to the special offers page. Then we need 3 boxes below with Recommend a friend, Twin package and Loyality scheme.

Lastly the hospitals banner at the bottom. Can you make it sit exactly like how I've done it for the Swiss french with the text on top of the box rather than above the box.

Then we need to create the special offers page like this page http://fhbb.staging.wpengine.com/ch-fr/blog/offre-speciale/. You can get the content from this page http://www.futurehealthbiobank.ch/gutschein

Can you then link the homepage banner, first slide to the special offers page. The copy should be the same as the old swiss german website.

Big text: SPEZIAL-ANGEBOT FÜR SEPTEMBER
Small text: Bei jeder Bestellung eines Kits bis 30.
September erhalten Sie 10% Rabatt.
Link: Erfahren Sie mehr

Let me know if you need to run through this further.

**Comment by mcatena** [comment]
HI,
all done

http://fhbb.staging.wpengine.com/ch-de/blog/hilfe/spezial-angebet/
http://fhbb.staging.wpengine.com/ch-de/blog/hilfe/

**Comment by maricarstubley** [comment]
Delete full stop in title

**Comment by mcatena** [comment]
Done
