### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#267]
At the top of the about us page can you change the headline to 
'We are the only private bank with a laboratory in Switzerland, certified by Swissmedic'

**Comment by maricarstubley** [comment]
Can you take out the bit where it says
'The Future Health Biobank seed was planted just over 17 years ago, following three years of extensive research into this potentially-lifesaving service, our doors finally opened for the first time in 2002. Headquartered in Nottingham; the heart of the UK, we were one of the first companies to offer customers umbilical cord stem cell banking.'

**Comment by maricarstubley** [comment]
Can you change this section:
Future Health Biobank is now the UK’s largest stem cell bank, having processed and stored more samples than all other UK banks combined. With over 125’000 samples from over 75 different countries, you can be confident that your sample is processed by the country’s most experienced and trusted bank.

To:

Future Health Biobank is Switzerland and UK’s largest stem cell bank. With more than 125’000 samples from over 75 different countries, you can be confident that your sample is processed by the country’s most experienced and trusted bank.

**Comment by mcatena** [comment]
Done
