### ISSUE TITLE
Our global family

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#270]
Can you change the sub text from Storing more than 125'000 samples from over 75 different countries, more than all other UK banks combined to Storing more than 125'000 samples from over 75 different countries

**Comment by maricarstubley** [comment]
Can you amend where it says The UK’s only family stem cell bank to own and operate two laboratories in two European countries

To: 
The only stem cell bank to own and operate two laboratories in two European countries

**Comment by mcatena** [comment]
Done
