### ISSUE TITLE
Umbilical cord stem cell banking - Why choose us

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#273]
On this page http://fhbb.staging.wpengine.com/ch-en/our-services/stem-cell-banking/umbilical-cord-stem-cell-banking in the why choose us section please swap UK's largest... to 

![Screen Shot 2016-09-28 at 14.26.56.png](https://zube.io/files/maricarstubley/3af3743cb2ce61b929bad8d2b2d7b386.png)

**Comment by mcatena** [comment]
Done
