### ISSUE TITLE
Adipose tissue

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#275]
http://fhbb.staging.wpengine.com/ch-en/our-services/stem-cell-banking/adipose-tissue-stem-cell-banking/
![Screen Shot 2016-09-28 at 14.34.12.png](https://zube.io/files/maricarstubley/636544d1f8e2ab94a4c24bffe96b68ab.png)

Take the MSC so it just says Clinical trials

**Comment by maricarstubley** [comment]
Same amend for this page http://fhbb.staging.wpengine.com/ch-en/our-services/stem-cell-banking/dental-pulp-cell-banking/

**Comment by mcatena** [comment]
Done
