### ISSUE TITLE
Adipose tissue processing

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#276]
Change where it says -150 to -190

http://fhbb.staging.wpengine.com/ch-en/our-services/stem-cell-banking/adipose-tissue-stem-cell-banking/adipose-tissue-processing/

**Comment by maricarstubley** [comment]
Same amend for this page http://fhbb.staging.wpengine.com/ch-en/our-services/stem-cell-banking/dental-pulp-cell-banking/dental-pulp-processing/

**Comment by maricarstubley** [comment]
This page hasn't been amended http://fhbb.staging.wpengine.com/ch-en/our-services/stem-cell-banking/dental-pulp-cell-banking/dental-pulp-processing/

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
It says -190c. What is that? Please check before sending for review.

**Comment by mcatena** [comment]
Done
