### ISSUE TITLE
Missing graphic

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#277]
http://fhbb.staging.wpengine.com/ch-fr/nos-services/diagnostics/test-prenatal-non-invasif/processus-du-test-nipt/

Step 5 should the text in the graphic

**Comment by mcatena** [comment]
We used that graphics for all the website to avoid the request of translation

**Comment by maricarstubley** [comment]
Okay but why is there a yellow line there? Doesn't that look a bit odd?

**Comment by mcatena** [comment]
OK we need to ask to Cp to amend it...

**Comment by maricarstubley** [comment]
No, you've added it here.

http://fhbb.staging.wpengine.com/pt/servicos/testes-de-diagnostico/teste-pre-natal-nao-invasivo/o-processo-do-teste-tpni/

**Comment by mcatena** [comment]
Done
