### ISSUE TITLE
The NIPT test process

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#278]
http://fhbb.staging.wpengine.com/ch-en/our-services/diagnostics/non-invasive-prenatal-test/nipt-test-process/

The text in the why choose us section isn't the same size or colour.
![Screen Shot 2016-09-28 at 14.46.04.png](https://zube.io/files/maricarstubley/da36a1274a6fd56c3a6005c59210acac.png)

**Comment by maricarstubley** [comment]
Same with this page http://fhbb.staging.wpengine.com/ch-en/our-services/diagnostics/non-invasive-prenatal-test/nipt-screening-results/

**Comment by maricarstubley** [comment]
Same with this page http://fhbb.staging.wpengine.com/ch-en/our-services/diagnostics/non-invasive-prenatal-test/nipt-competitor-chart/

**Comment by mcatena** [comment]
Done
