### ISSUE TITLE
Non Invasive Prenatal Test

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#279]
http://fhbb.staging.wpengine.com/ch-en/our-services/diagnostics/non-invasive-prenatal-test/

Change this test please:
Another key benefit to Vision is related to the accuracy of gender identification. From as early as 10 weeks into a pregnancy, this test can detect whether the baby is a boy or a girl. This test has an accuracy rate of 99%. This information is not normally disclosed on the NHS until the 20 week ultrasound scan and is often not guaranteed to be an accurate result, so surprises are still possible.

To:

Another key benefit to Vision is related to the accuracy of gender identification. From as early as 10 weeks into a pregnancy, this test can detect whether the baby is a boy or a girl. This test has an accuracy rate of 99%. This information is not normally disclosed until the 20 week ultrasound scan and is often not guaranteed to be an accurate result, so surprises are still possible.

**Comment by maricarstubley** [comment]
Also please take the full stop out in the headline

**Comment by mcatena** [comment]
Done
