### ISSUE TITLE
Down’s syndrome

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#280]
Where you see this and others can there be a capital D in diagnostics

![Screen Shot 2016-09-28 at 14.55.38.png](https://zube.io/files/maricarstubley/0882da5832faa94a7a646a28894235de.png)

**Comment by maricarstubley** [comment]
Here a few places it's in:
http://fhbb.staging.wpengine.com/ch-en/our-services/diagnostics/non-invasive-prenatal-test/downs-syndrome/

http://fhbb.staging.wpengine.com/ch-en/our-services/diagnostics/non-invasive-prenatal-test/edwards-syndrome/

http://fhbb.staging.wpengine.com/ch-en/our-services/diagnostics/non-invasive-prenatal-test/pataus-syndrome/

**Comment by mcatena** [comment]
Done
