### ISSUE TITLE
Jacob’s syndrome

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#281]
Can you add a title to the top section. It should say 'What is Jacob's syndrome'
http://fhbb.staging.wpengine.com/ch-en/our-services/diagnostics/non-invasive-prenatal-test/jacobs-syndrome/

Can you do it for the others too please including Klinefelter etc.

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
This isn't done as there are 3 that needs doing.

**Comment by mcatena** [comment]
Done but on Uk one the title are not present

**Comment by maricarstubley** [comment]
No, so it should be added aswell, shouldn't it? As I keep saying all needs to be consistent.

**Comment by maricarstubley** [comment]
Just noticed there's a full stop in the headline on this page http://fhbb.staging.wpengine.com/ch-en/our-services/diagnostics/non-invasive-prenatal-test/

**Comment by mcatena** [comment]
I notice too and i already amended

**Comment by mcatena** [comment]
Added in uk too

**Comment by maricarstubley** [comment]
Is the title of this page http://fhbb.staging.wpengine.com/ch-en/our-services/diagnostics/non-invasive-prenatal-test/edwards-syndrome/ in a different box? If you compare it with another intolerance the title is further down.

**Comment by mcatena** [comment]
Now should be the same..
