### ISSUE TITLE
Umbilical cord stem cell banking prices

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#283]
Add the text:
Recieve a 200CHF discount for payment up front

http://fhbb.staging.wpengine.com/ch-fr/tarifs/prix-de-la-banque-de-cellules-souches/prix-du-cordon-ombilical/

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Could you re-amend please.

Add this as big text: Stammzellen sind die Bausteine des Lebens. Sie stellen einen direkten Bezug zwischen der Gesundheit Ihres Kindes zum Zeitpunkt der Geburt und in der Zukunft her.

And take out of the first paragraph.
