### ISSUE TITLE
Dental Pulp prices

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#284]
http://fhbb.staging.wpengine.com/ch-en/pricing/stem-cell-banking-prices/dental-pulp-cell-banking-prices/

Please copy the left and right boxes to match the CH-FR - http://fhbb.staging.wpengine.com/ch-fr/tarifs/prix-de-la-banque-de-cellules-souches/prix-de-la-pulpe-dentaire/. Obviously it will need to be english rather than Swiss French

**Comment by maricarstubley** [comment]
Sorry, I just saw on another page what you had added. 

Can you please have 'Contact us on' so it's consistent rather than 'Call us' as you have on this page http://fhbb.staging.wpengine.com/pricing/diagnostics-prices/new-born-screening-prices/. This page will therefore need amending aswell.

And also the same with this page http://fhbb.staging.wpengine.com/ch-en/pricing/diagnostics-prices/nipt-prices/

**Comment by maricarstubley** [comment]
Sorry, I just saw on another page what you had added. 

Can you please have 'Contact us on' so it's consistent rather than 'Call us' as you have on this page http://fhbb.staging.wpengine.com/pricing/diagnostics-prices/new-born-screening-prices/. This page will therefore need amending aswell.

**Comment by maricarstubley** [comment]
The price going through to basket is still wrong. It needs to go through as 480 as mentioned earlier. Currently going through as £295.

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Sorry, please amend to 'Contact us on' and I've just noticed a colon after the email. Can you remove it please. These need to be amended for both UK and CH-EN.

**Comment by mcatena** [comment]
it's not clear to me what you are asking....should be "Contact us on" or only "Contact us"?

**Comment by mcatena** [comment]
Done
