### ISSUE TITLE
Non Invasive Prenatal Test prices

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#285]
http://fhbb.staging.wpengine.com/ch-en/pricing/diagnostics-prices/nipt-prices/

Can you amend the right box to say 'October Special at CHF 799 .--'

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Sorry, this should still have 15% discount pink and in the black text 'October Special at CHF 799 .--'

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Can you put a break after 'at' so 799 .-- is on the next line as it looks odd doesn't it?

**Comment by mcatena** [comment]
Done
