### ISSUE TITLE
Special offers

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#288]
http://fhbb.staging.wpengine.com/ch-de/blog/hilfe/spezial-angebet/

Could you amend the telephone number to Tel: 021 948 2 948

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Can you have a look again please? There's an extra full stop after Tel. I've only added Tel: 021 948 2 948 as above.

**Comment by mcatena** [comment]
Done
