### ISSUE TITLE
Helping hand

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#289]
http://fhbb.staging.wpengine.com/ch-en/blog/a-helping-hand/

Can you amend the text: At Future Health Biobank we are proud to offer our umbilical cord stem cell collection service from almost every hospital in the UK

To: 
At Future Health Biobank we are proud to offer our umbilical cord stem cell collection service in all hospitals in the Switzerland.

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Can you change the hospital section to segment 14 to keep consistent with the other countries and the do the same for the rest of the countries going forward.

**Comment by mcatena** [comment]
Done..for the restyle of this page in CH-EN there is another tck

**Comment by maricarstubley** [comment]
Okay, if it's a duplicate can you close it as I probably just forgot

**Comment by maricarstubley** [comment]
I noticed the urls are slightly different to the uk version http://fhbb.staging.wpengine.com/blog/a-helping-hand/

There's no A before helping hand, same with title.

**Comment by mcatena** [comment]
Already changed

**Comment by maricarstubley** [comment]
I don't think I can see this has been changed. The link throws a page not found error.

**Comment by mcatena** [comment]
Ah ok i changed the CH-EN is why...now Uk is ready

**Comment by maricarstubley** [comment]
Oh right, I think we're a bit confused.

Both needs to have in the url a-helping-hand
In the title it needs to have A helping hand

As UK is already live we should not change the URL unless neccessary so unfortunately we will need to stick to A helping hand not Helping hand. Hope this makes sense.

**Comment by maricarstubley** [comment]
Please amend as discussed in CH-FR. Still not correct.

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
It's showing a 404

**Comment by mcatena** [comment]
Now is ok
