### ISSUE TITLE
Precios page

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#29]
http://fhbb.staging.wpengine.com/es/precios/

Please change 'Sabemos que tener un hijo puede ser caro, así que ofrecemos diversas opciones de pago, incluyendo planes de pago sin intereses.' to 'Sabemos que tener un hijo conlleva muchos gastos, así que ofrecemos diversas opciones de pago, incluyendo planes de pago sin intereses.'

**Comment by mcatena** [comment]
Changed
