### ISSUE TITLE
Advice Panel

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#294]
Please use the same why choose us picture below on this page http://fhbb.staging.wpengine.com/ch-en/advice-panel/. Obviously these will need to be in english.

![Screen Shot 2016-09-28 at 17.03.22.png](https://zube.io/files/maricarstubley/c7d33df716e13ed7d1d561e46e3f0294.png)

**Comment by mcatena** [comment]
Done
