### ISSUE TITLE
Advice panel - When can I contact the customer care team?

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#295]
http://fhbb.staging.wpengine.com/ch-en/advice-panel/stem-cell-banking-advice/can-i-contact-customer-care-team/
1. Please take out the full stop in the header.
2. Delete only the paragraph: A great way to get to know our brand a little better is by attending one of the many baby shows where we exhibit. These shows are normally scattered throughout the country from Birmingham to London. If you are nearby then please do pop in and say hello, our team are always happy to meet old and new customers.
3. The second and third paragraph seems to be clickable and linking. Please take out the link.
4. Under Help and advice the middle box has a missing image for me. See screenshot below.

![Screen Shot 2016-09-28 at 17.13.01.png](https://zube.io/files/maricarstubley/7e39c6853f8039e63215bdfbcdd41649.png)

**Comment by mcatena** [comment]
Done
