### ISSUE TITLE
Beratung

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#296]
http://fhbb.staging.wpengine.com/ch-de/beratung/
1. Take out full stop in headline
2. Where it says 'Hören Sie, was unsere Kunden zu sagen haben' this should be consistent with the rest of segment 9 which is 'Erfahren Sie von unseren Kunden'. I've noticed that this has been different for a few of the websites recently so please can you make sure this is always something you look out for.
3. Change the 'Why choose us' section to the german versions. See screenshots below.

![Screen Shot 2016-09-28 at 18.45.50.png](https://zube.io/files/maricarstubley/9bbd14911f07a47493b0ba83d1bf56b1.png)

**Comment by mcatena** [comment]
Done
