### ISSUE TITLE
Auswahl einer verlässlichen Stammzellenbank

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#298]
http://fhbb.staging.wpengine.com/ch-de/beratung/beratungsbereich-stammzellenbank/auswahl-einer-verlasslichen-stammzellenbank/
1. Take out full stop on main header
2. Add the grey line after the sentence 'Deshalb haben wir eine Liste mit den wesentlichen Merkmalen zusammengestellt, die Sie berücksichtigen sollten, wenn Sie eine verlässliche Stammzellenbank auswählen.' to break up the sections

**Comment by mcatena** [comment]
Done
