### ISSUE TITLE
Text change

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#30]
http://fhbb.staging.wpengine.com/es/precios/precios-de-conservacion-de-celulas-madre-del-cordon-umbilical/

Please change 'Como sabemos que tener un hijo puede ser caro, les ofrecemos planes de pago sin intereses a 6, o 12 meses.' to 'Como sabemos que tener un hijo conlleva muchos gastos, les ofrecemos planes de pago sin intereses a 6, o 12 meses.'

**Comment by mcatena** [comment]
Changed
