### ISSUE TITLE
Was sind Nabelschnurstammzellen?

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#300]
http://fhbb.staging.wpengine.com/ch-de/beratung/beratungsbereich-stammzellenbank/was-sind-nabelschnurstammzellen/

Could you re-amend please.

Add this as big text: Stammzellen sind die Bausteine des Lebens. Sie stellen einen direkten Bezug zwischen der Gesundheit Ihres Kindes zum Zeitpunkt der Geburt und in der Zukunft her.

And take out of the first paragraph.

**Comment by mcatena** [comment]
Done
