### ISSUE TITLE
Adipose tissue stem cell banking prices

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#317]
On this page http://fhbb.staging.wpengine.com/ch-en/pricing/stem-cell-banking-prices/adipose-tissue-stem-cell-banking-prices/ can you add the same information on the left and right boxes as we have for this page http://fhbb.staging.wpengine.com/ch-en/pricing/diagnostics-prices/new-born-screening-prices/

**Comment by mcatena** [comment]
Done
