### ISSUE TITLE
Perchè scegliere noi

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#319]
Reorder http://fhbb.staging.wpengine.com/ch-it/chi-siamo/perche-scegliere-noi/ to match the CH-FR http://fhbb.staging.wpengine.com/ch-fr/a-propos-de-nous/pourquoi-nous-choisir/

**Comment by mcatena** [comment]
Done but waiting an cusp's to finish

**Comment by mcatena** [comment]
Done
