### ISSUE TITLE
I nostri servizi

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#321]
On this page http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/
1. Change Conservazione delle cellule staminali to Conservazione cellule staminali
2. 
   Change:
   La conservazione delle cellule staminali: un servizio potenzialmente salva-vita. Proteggi la salute futura della tua famiglia

To: Conserva le cellule staminali, proteggi la salute futura della tua famiglia.

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
Can you change the why choose us on this page to be the same as the CH-FR please. See below screenshot.

![Screen Shot 2016-09-30 at 10.26.10.png](https://zube.io/files/maricarstubley/afe5fbfa026f053ed06c62ee2dcfafa1.png)

**Comment by mcatena** [comment]
Done
