### ISSUE TITLE
Conservazione delle cellule staminali del sangue e del tessuto cordonale

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#323]
On this page http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-delle-cellule-staminali-del-sangue-e-del-tessuto-cordonale/
1. Change H1 title to Conservazione cordone ombelicale and change the URL to match the title
2. In the banner change big text to 'Conservazione sangue e tessuto cordonale' and small text to 'Questo è il nostro servizio più richiesto'
3. For Sangue cordonale add sub text: Le cellule staminali del sangue cordonale sono già in uso per il trattamento di oltre 85 patologie tra cui leucemie, anemie e talassemie
4. For Tessuto cordonale add sub text: Le possibilità di utilizzo delle cellule staminali del tessuto cordonale sono in continua crescità ed attualmente sono in corso più di 300 sperimentazioni cliniche.
5. Copy 'Why choose us' section from http://fhbb.staging.wpengine.com/ch-fr/nos-services/banque-de-cellules-souches/cellules-souches-du-cordon-ombilical/

**Comment by mcatena** [comment]
The third box of why choose us need to be amended with swissmedic

**Comment by mcatena** [comment]
Yes was yesterday so i just done the check in all website so yes is done

**Comment by mcatena** [comment]
Complete
