### ISSUE TITLE
Conservazione delle cellule staminali del sangue e del tessuto cordonale

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#324]
On this page http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-delle-cellule-staminali-del-sangue-e-del-tessuto-cordonale/conservazione-delle-cellule-staminali-del-sangue-e-del-tessuto-cordonale/
1. Change the h1 title to Conservazione sangue e tessuto cordonale
2. Change the URL to match the title
3. Copy the content from this page http://fhbb.staging.wpengine.com/it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-sangue-e-tessuto-cordonale/. The bulk content and USPs have slight changes.

**Comment by mcatena** [comment]
I copied the main contents i m not sure if i have to copy everything or is ok like that

**Comment by maricarstubley** [comment]
Can you screen shot what you can see please? Might be easier for me to see.

**Comment by mcatena** [comment]
This is the only part i updated....no others sections
![Screen Shot 2016-09-30 at 08.55.02.png](https://zube.io/files/maricarstubley/6a957d94fa9493cd05341942e9bef183.png)
