### ISSUE TITLE
Processo di raccolta delle cellule staminali del cordone ombelicale

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#328]
On this page http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-sangue-e-tessuto-cordonale/processo-di-raccolta-delle-cellule-staminali-del-cordone-ombelicale/
1. Change the h1 title and url to Raccolta cellule staminali cordonali
2. Copy the rest of the content to be the same as http://fhbb.staging.wpengine.com/it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-sangue-e-tessuto-cordonale/raccolta-cellule-staminali-cordonali/

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
The title is massive.

**Comment by mcatena** [comment]
now is ok...wrong line sorry

http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-sangue-e-tessuto-cordonale/raccolta-cellule-staminali-cordonali/
