### ISSUE TITLE
Conservazione delle cellule staminali del sangue cordonale

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#329]
On this page http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-delle-cellule-staminali-del-sangue-cordonale/
1. Change the h1 title and url to 'Conservazione sangue cordonale'
2. Where it starts 'Queste cellule preziose si raccolgono dal cordone ombelicale' copy and paste the text from this page http://fhbb.staging.wpengine.com/it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-sangue-cordonale/

**Comment by mcatena** [comment]
Done
