### ISSUE TITLE
Diagnostics pricing page

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#33]
http://fhbb.staging.wpengine.com/es/precios/precios-de-servicio-de-diagnosticos/

Where have you got the translation for this page from?

**Comment by mcatena** [comment]
From the spreadsheet in other section...the two title are always the same and the button eather...probably the page title is not correct but i have done it before they complain about google translation to take advantage

**Comment by maricarstubley** [comment]
Can you keep in your to do as this still needs looking at

**Comment by mcatena** [comment]
Put the english rice for now
