### ISSUE TITLE
Processo di raccolta delle cellule staminali del sangue cordonale

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#330]
On this page http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-delle-cellule-staminali-del-sangue-cordonale/processo-di-raccolta-delle-cellule-staminali-del-sangue-cordonale/
1. Change the h1 title and url to 'Raccolta sangue cordonale'
2. Amend the content to be the same as this page http://fhbb.staging.wpengine.com/it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-sangue-cordonale/raccolta-sangue-cordonale/.

**Comment by mcatena** [comment]
Done

**Comment by mcatena** [comment]
http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-sangue-cordonale/raccolta-sangue-cordonale/
