### ISSUE TITLE
Conservazione delle cellule staminali del tessuto cordonale

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#331]
On this page http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-delle-cellule-staminali-del-tessuto-cordonale/
1. Change the h1 title and url to 'Conservazione tessuto cordonale'
2. Where the text starts 'Attualmente sono in corso oltre 300...' Copy and paste text from this page http://fhbb.staging.wpengine.com/it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-tessuto-cordonale/

**Comment by mcatena** [comment]
Done
