### ISSUE TITLE
Processo di raccolta delle cellule staminali del tessuto cordonale

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#332]
On this page http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-delle-cellule-staminali-del-tessuto-cordonale/processo-raccolta-delle-cellule-staminali-del-tessuto-cordonale/
1. Change the h1 title and url to 'Raccolta tessuto cordonale'
2. Make the content the same as this page http://fhbb.staging.wpengine.com/it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-tessuto-cordonale/raccolta-tessuto-cordonale/

**Comment by mcatena** [comment]
Done

**Comment by mcatena** [comment]
http://fhbb.staging.wpengine.com/ch-it/i-nostri-servizi/conservazione-delle-cellule-staminali/conservazione-cordone-ombelicale/conservazione-tessuto-cordonale/raccolta-tessuto-cordonale/
