### ISSUE TITLE
Advice panel

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#37]
http://fhbb.staging.wpengine.com/es/blog/opiniones-de-nuestros-clientes/como-elegir-un-banco-de-celulas-madre-fiable/

Please remove the extra full stop after 'Nuestras acreditaciones'
Segment 24 has english content

**Comment by maricarstubley** [comment]
Segment 24 has english content in it

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/consejos-en-conservacion-de-celulas-madre/mas-fondos-para-la-investigacion-de-celulas-madre-de-la-sangre-del-cordon/

Add paragraphs. I mentioned this before.

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/consejos-en-conservacion-de-celulas-madre/un-paso-mas-cerca-del-tratamiento-de-la-paralisis-cerebral-con-celulas-madre/

Add paragraphs. I mentioned this before.

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/consejos-en-conservacion-de-celulas-madre/cuando-puedo-contactar-con-el-equipo-de-atencion-al-cliente/

Please note that the 'Conozca al equipo' infography/section does not apply in Spain

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/consejos-en-conservacion-de-celulas-madre/prometedores-resultados-del-tratamiento-de-la-eadr-con-celulas-madre/

Add paragraphs. I mentioned this before.

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/consejos-de-diagnostico/

There are 13 diagnostics advice translated, but you've only put 9?
The first advice headline is incorrect, you've used Google translated content

**Comment by mcatena** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/consejos-en-conservacion-de-celulas-madre/cuando-puedo-contactar-con-el-equipo-de-atencion-al-cliente/ could you please ask what put in instead of 'Conozca al equipo' infography

http://fhbb.staging.wpengine.com/es/panel-informativo/consejos-de-diagnostico/ is exactly the same of english version. Shell we put all of the advice in?

All the other are ok

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/panel-informativo/consejos-en-conservacion-de-celulas-madre/cuando-puedo-contactar-con-el-equipo-de-atencion-al-cliente/

Could you remove this please?

**Comment by mcatena** [comment]
13:44 Just checked all and all with paragraphs
