### ISSUE TITLE
Request a brochure

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#38]
http://fhbb.staging.wpengine.com/es/solicitar-informacion/

Why is this different from the excel sheet?
Also the form fields are different to the UK aswell. When you get to this please tell me when it's done. I have to test this tomorrow.

**Comment by mcatena** [comment]
if you take look inside the contact forms backend you can see that this one [contact-form-7 id="763" title="Solicitar información"] is the same of the spread sheet
