### ISSUE TITLE
Meta description URLs

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#40]
Can you take a look at the file I sent you before I went on holiday. The URLs need to follow what's been added. It's for SEO purposes and we need to stick to this.

**Comment by mcatena** [comment]
Done...please check if everything is in because i could miss something......Plus i have no content for the blog...

**Comment by maricarstubley** [comment]
@arobinson-fhbb Could you check please?

**Comment by arobinson-fhbb** [comment]
@maricarstubley Shuttlebrand are checking this for us today and will let us know any amends

**Comment by maricarstubley** [comment]
@mcatena Please check through the list thoroughly to ensure the links are the same references from the URL on meta description

**Comment by mcatena** [comment]
@maricarstubley Checked all following the last spreadsheet you sent to me.

missing SEO for all testimonials

**Comment by maricarstubley** [comment]
I've sent you some for testimonials

**Comment by mcatena** [comment]
done

**Comment by mcatena** [comment]
@maricarstubley  i need meta description of the new one
