### ISSUE TITLE
Why choose us USPs

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#42]
Can you go through all the why choose us sections. We should only be using what they have provided in the excel sheet.

**Comment by mcatena** [comment]
Checked and changed the only infonographic that wasn't matched with the list in the spreadsheet.....i will change the others in the others pages soon i ll see them

**Comment by maricarstubley** [comment]
@mcatena this isn't what we discussed earlier. Please amend to what I have requested above and don't put it in for review until it's complete.

**Comment by mcatena** [comment]
Changed in all website with the usp included in spanish spreadsheet

**Comment by mcatena** [comment]
Need translation of the USP in this page
http://fhbb.staging.wpengine.com/es/ the one in the middle
