### ISSUE TITLE
Payment is still in english

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#63]
http://fhbb.staging.wpengine.com/es/servicios/diagnosticos/test-prenatal-no-invasivo/prueba-sindrome-de-down-embarazo/

Please amend

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/servicios/diagnosticos/screening-neonatal/enfermedad-celiaca/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/servicios/diagnosticos/screening-neonatal/intolerancia-a-la-lactosa/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/servicios/diagnosticos/screening-neonatal/intolerancia-a-la-fructosa/

**Comment by maricarstubley** [comment]
http://fhbb.staging.wpengine.com/es/servicios/diagnosticos/screening-neonatal/hemocromatosis/

**Comment by mcatena** [comment]
Need translation

**Comment by mcatena** [comment]
http://fhbb.staging.wpengine.com/es/servicios/diagnosticos/test-prenatal-no-invasivo/carta-competidor-nipt/

**Comment by mcatena** [comment]
http://fhbb.staging.wpengine.com/es/servicios/diagnosticos/test-prenatal-no-invasivo/funcionamiento-del-test-vision/

**Comment by mcatena** [comment]
Update all the pages with the translation in the spreadsheet...
