### ISSUE TITLE
Pages is still english

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#76]
http://fhbb.staging.wpengine.com/es/servicios/diagnosticos/test-prenatal-no-invasivo/los-resultados-del-cribado-nipt/

This page has half got english and half spanish. I'm sure where you've already got the content you can add these in here.

**Comment by mcatena** [comment]
I don't have content in my spreadsheet...Please ask for the translation

**Comment by maricarstubley** [comment]
@mcatena please add content where you can as requested above. 

I have sent this to be looked at and translated and will get these to you when I have it.

**Comment by mcatena** [comment]
Done
