### ISSUE TITLE
Can why choose go to Vision

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#77]
http://fhbb.staging.wpengine.com/es/servicios/diagnosticos/test-prenatal-no-invasivo/carta-competidor-nipt/

**Comment by arobinson-fhbb** [comment]
Yes it needs to go to the Vision landing page. This is how the UK works, so needs to mimic that please

**Comment by mcatena** [comment]
Sorry i put the task in the wrong review ;)

**Comment by maricarstubley** [comment]
@mcatena - Apologies my title wasn't very clear!

Can the "Why choose us" section link to the Vision page
