### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#78]
The Sordera inducida por fármacos on ths page http://fhbb.staging.wpengine.com/es/servicios/diagnosticos/screening-neonatal/ is broken

**Comment by maricarstubley** [comment]
The stem cell banking isn't linking http://fhbb.staging.wpengine.com/es/precios/

**Comment by mcatena** [comment]
The stem cell banking isn't linking http://fhbb.staging.wpengine.com/es/precios/  link to this pages as uk is : http://fhbb.staging.wpengine.com/es/precios/precios-de-conse…de-celulas-madre/
