### ISSUE TITLE
Update UK thank you pages

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#80]
Can you update UK's thank you pages please and the test the forms. I would do one first as it may change and let me know when you've done the first one so I can see.

**Comment by mcatena** [comment]
Images changed and tested...email received

**Comment by maricarstubley** [comment]
@mcatena Same amends for UK as the Spanish version. There should be no line or title as it's a duplicate of the H1 and line above.

Catherine hasn't done the amends to these yet so you will have to wait until she lets me know when she is ready.

**Comment by maricarstubley** [comment]
Can you update these with the new ones 13-thank you pages in UK folder
