### ISSUE TITLE
Add Spain thank you pages

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#83]
These pages do not currenty exist. Can you make these pages? Also are you able to take the page name from the image? If not then can you make up the pages in english. 

Just so you know here's what I have for the english links. Obviously if you are to add this then there would be no hypens.

thanks-getting-touch
thanks-for-signing-up-to-our-newsletter
thanks-for-requesting-a-brochure

 You can find the images you need to use in the ES > 10 - Thank you pages
If any changes to the title, reply here as I need to change the names of the pages in the form settings

**Comment by mcatena** [comment]
i need the translation of the titles
http://fhbb.staging.wpengine.com/es/thanks-for-getting-in-touch/

http://fhbb.staging.wpengine.com/es/thanks-for-requesting-a-brochure/

http://fhbb.staging.wpengine.com/es/thanks-signing-newsletter/

**Comment by maricarstubley** [comment]
@mcatena looks like the titles are in the artwork. Please check and amend,

**Comment by maricarstubley** [comment]
@mcatena are these the same page names?

**Comment by mcatena** [comment]
http://fhbb.staging.wpengine.com/es/gracias-por-solicitar-mas-informacion/
http://fhbb.staging.wpengine.com/es/gracias-por-su-mensaje/
http://fhbb.staging.wpengine.com/es/gracias-por-subscribirse-a-nuestro-boletin/

**Comment by maricarstubley** [comment]
@mcatena Can you look through 10 - Thank you pages in folder and find the ones with no title. It looks odd that the title is similar to each other.
