### ISSUE TITLE
Section change in Helping hand

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#84]
![Screen Shot 2016-05-26 at 14.14.07.png](https://zube.io/files/maricarstubley/81b7069925c9c544234e9e80e5bc81a7.png)

On this page: http://fhbb.staging.wpengine.com/es/blog/precios-especiales/ can you turn the section I've sreenshot into segment 3 and have Programa de fidelización on the left and Paquete gemelar on the right please.

You will need to ask Catherine to amend the sizes.

All links should stay the same.

**Comment by mcatena** [comment]
Done....i done the images....
