### ISSUE TITLE
Update the payment icon

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#85]
![pricing_ES.png](https://zube.io/files/maricarstubley/507c042b2085ae1cd40af12265300ba9.png) Where the above graphic exists can you update please?

Thanks Maz

**Comment by maricarstubley** [comment]
![pricing_reverse_ES.png](https://zube.io/files/maricarstubley/ef2cd6d80de9da3ba99ca5098f3d29e3.png)

The reversed option

**Comment by mcatena** [comment]
Need to be update in the purple box....but i can not do it in front-end
