### ISSUE TITLE
Interesess has two s's in the url and 1 s in the H1

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#94]
http://fhbb.staging.wpengine.com/es/plan-de-pago-sin-interesess/

Is this correct?

**Comment by maricarstubley** [comment]
Could you add the interest free payment illustration we have around the site and add to the banner here. 

Uk is also missing so could you update the banner there too http://fhbb.staging.wpengine.com/interest-free-payment-plan/

**Comment by mcatena** [comment]
Done in portugal too
