### ISSUE TITLE
404 pages

### ISSUE THREAD

**Issue by maricarstubley** [maricarstubley/fhbb-ticket#95]
http://fhbb.staging.wpengine.com/es%20/page-cannot-be-found/

Can you update please. Ask Catherine where this saved?

**Comment by mcatena** [comment]
Done

**Comment by maricarstubley** [comment]
@mcatena should this still be with you?

**Comment by mcatena** [comment]
I think now are done

**Comment by maricarstubley** [comment]
Doesn't look like it is to me.

**Comment by mcatena** [comment]
Done...consistent with the new format used for spain
